version: '3'
services:

  # PYTHON ENV & DJANGO 
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: web
    command: ./run_web.sh
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    links:
      - redis
      - db

  # REDIS
  redis:
    image: redis:5.0
    ports:
      - 6379:6379

  # CELERY WORKER
  # celery:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   command: celery -A multitest worker -l info
  #   volumes:
  #     - ./src:/src
  #   ports:
  #     - 5555:5555
  #   links:
  #     - redis

  # MONGODB
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017-27019:27017-27019